name: Build release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Get tag name
      id: get_tag_name
      run: |
        echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
    - name: Create directory
      run: |
        mkdir -p target/release
    - name: Compress into zip
      uses: vimtor/action-zip@v1
      with:
        files: Setup-CompassOfWomanhood.exe CompassOfWomanhood/
        dest: target/release/CompassOfWomanhood.zip
        recursive: false
    - name: Compress into tarball
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: "./"
        files: |
          Setup-CompassOfWomanhood.exe
          CompassOfWomanhood/
        outPath: target/release/CompassOfWomanhood.tar.gz
    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: target/release/CompassOfWomanhood.zip
        asset_name: CompassOfWomanhood-${{ steps.get_tag_name.outputs.TAG_NAME }}.zip
        overwrite: true
        body: "Game files (zip)"
    - name: Upload tarball to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: target/release/CompassOfWomanhood.tar.gz
        asset_name: CompassOfWomanhood-${{ steps.get_tag_name.outputs.TAG_NAME }}.tar.gz
        overwrite: true
        body: "Game files (tarball)"
