name: Build And Deploy Landing Page

on:
  push:
    branches: [ "main" ]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: LandingPage
    name: Build Vue
    steps:
      - uses: actions/checkout@v3
      - name: Build Vue
        run: |
          yarn install --frozen-lockfile
          yarn build
          cd dist
          ln -s index.html 404.html
          git config --global user.email "${{ env.gitemail }}"
          git config --global user.name "${{ env.gitname }}"
          git init
          git add -A
          git commit -m '${{ env.gitmsg }}'
          git push -f https://${{ github.repository_owner }}:${{ env.token }}@github.com/${{ github.repository }}.git master:gh-pages
        env:
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          gitemail: publisher@udiknedormin.github.io
          gitname: Github Page Publisher [bot]
          gitmsg: Publishing pages for job ${{ github.workflow }}
